spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/lingodb
    username: root
    password: pwd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  jwt:
    secret: 636E385229FF3D2E43E4362356D1fggQweRT123 #HS256 (key >= 32*8)
server:
  port: 8081
logging:
  level:
    org.example: DEBUG