/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import org.junit.jupiter.api.Test;

import static org.hibernate.validator.internal.util.Contracts.assertNotNull;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();

    }
}
